#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# If the folder we're in is called bublic, it means we're a submodule in the private repo.
# We need to grab .envrc to set up yarn correctly.
current_file="$(readlink -f "$0")"
case "$current_file" in
  */bublic/.husky/pre-commit)
    . "$(dirname -- "$0")/../../.envrc"
    ;;
esac

npx lazy run build-api
git add packages/*/api-report.md
git add packages/*/api/api.json
npx lint-staged
